<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Country;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{

    public function run()
    {
        $countries_en = ['Saudi Arabia', 'Egypt'];
        $countries_ar = ['المملكة العربية السعودية', 'مصر'];

        //saudia cities
        $saudiaCities_en = [
            "Al Hamra",
            "Al Rawabi ",
            "Al Rawdah ",
            "Al Worood ",
            "Al Sulimania ",
            "Al Aziziyah ",
            "Al Olaya ",
            "Al Malaz",
            "Al Yarmouk ",
            "Al Olayya",
            "Al Aqrabeyah ",
            "Durat  Alarous",
            "Thybiyah",
            "Wadi Al Dawasir",
            "Al Bathah",
            "Al Shate'e",
            "Al Andalus",
            "Al Hamra ",
            "Al Rawda",
            "Al Salamah",
            "Al Mesfala",
            "Al Aziziya ",
            "Obhor",
            "Alkhaleej Village",
            "Al Jubail",
            "Riyadh",
            "Al Hada",
            "Thuwal",
            "Al Wudayy",
            "Abha",
            "Abu Arish",
            "Dammam",
            "Al Baha",
            "Al Bukayriyah",
            "Al Hofuf",
            "Hilwah",
            "Alkhafji",
            "Al Kharj",
            "Al Khobar",
            "Al Lith",
            "Medina",
            "Al Majmaah",
            "Al Ula",
            "Arar",
            "Ar Rass",
            "Taif",
            "Dhahran",
            "Baljurashi",
            "Birzayn",
            "Buraydah",
            "Farasan",
            "Hafa",
            "Hafr Al Baten",
            "Ha'il",
            "Jeddah",
            "Khamis Mushayt",
            "Mecca",
            "Mulayjah",
            "Najran",
            "Quai",
            "Rabigh",
            "Sakakah",
            "Salhabah",
            "Shaqra",
            "Sufaylah",
            "Tabuk",
            "Tathleeth",
            "Unayzah",
            "Yanbu",
            "Al Ahsa",
            "Al Wajh",
            "King Abdullah Economic City",
            "Kunfuda",
            "Muhayl",
            "Qurayyat",
            "Sharma",
            "Turaif",
            "Al Hasa",
            "AL AHSA",
            "AL JOUF",
            "AL KHAFJI",
            "AL QUWAIYAH",
            "BATUNA",
            "BELLONA",
            "BISHA",
            "BURAIDAH",
            "CHOISEUL BAY",
            "DAWADMI",
            "Saudi Arabia",
            "GASSIM",
            "GURAYAT",
            "HAFAR AL BATIN",
            "HAIL",
            "HOFUF",
            "JIZAN",
            "JOUF",
            "JUBAIL",
            "KING KHALID MIL CITY",
            "MADAIN SALEH",
            "MADINAH",
            "MAJMA",
            "Mecca City",
            "NEJRAN",
            "QAISUMAH",
            "QASSIM",
            "QATIF",
            "SEGE",
            "SHARURAH",
            "SULAYEL",
            "TURAIF",
            "WADI AD DAWASIR",
            "WEDJH",
            "ZILFI",
            "al-'Ula",
            "Hillah",
            "Sharurah",
            "Qatif",
            "Asir",
            "AL BAHAH",
            "KHAMIS MUSHAYAT",
            "MUHAYIL"
        ];
        $saudiaCities_ar = [
            "الحمراء",
            "الروابي",
            "الروضة",
            "الورود",
            "السليمانية",
            "العزيزية",
            "العليا",
            "الملز",
            "اليرموك",
            "العليا",
            "العقربية",
            "درة العروس",
            "ذبية",
            "وادي الدواسر",
            "البطحاء",
            "الشاطئ",
            "الأندلس",
            "الحمراء",
            "الروضة",
            "السلامة",
            "المسفلة",
            "العزيزية",
            "أبحر",
            "قرية الخليج",
            "الجبيل",
            "الرياض",
            "الهدا",
            "ثول",
            "الوديع",
            "أبها",
            "أبو عريش",
            "الدمام",
            "الباحة",
            "البكيرية",
            "الهفوف",
            "حلوة",
            "الخفجي",
            "الخرج",
            "الخبر",
            "الليث",
            "المدينة المنورة",
            "المجمعة",
            "العلا",
            "عرعر",
            "الرس",
            "الطائف",
            "الظهران",
            "بلجرشي",
            "بيرزين",
            "بريدة",
            "فرسان",
            "هافا",
            "حفر الباطن",
            "يشيد",
            "جدة",
            "خميس مشيط",
            "مكة المكرمة",
            "مليجة",
            "نجران",
            "قويا",
            "رابغ",
            "سكاكا",
            "سلابة",
            "شقراء",
            "سفيلة",
            "تبوك",
            "تثليث",
            "عنيزة",
            "ينبع",
            "الأحساء",
            "الوجه",
            "مدينة الملك عبد الله الاقتصادية",
            "القنفذة",
            "محايل",
            "قريات",
            "شارما",
            "طريف",
            "الأحساء",
            "الأحساء",
            "الجوف",
            "الخفجي",
            "القويعية",
            "باتونا",
            "بيلونا",
            "بيشا",
            "بريدة",
            "شوازول باي",
            "الدوادمي",
            "المملكة العربية السعودية",
            "قاسم",
            "القريات",
            "حفر الباطن",
            "يشيد",
            "هوفوف",
            "جيزان",
            "الجوف",
            "الجبيل",
            "مدينة الملك خالد ميل",
            "مدائن صالح",
            "المدينة المنورة",
            "ماجما",
            "مدينة مكة",
            "نجران",
            "القيصومة",
            "قاسم",
            "القطيف",
            "سيجا",
            "شرورة",
            "سولايل",
            "طريف",
            "وادي الدواسر",
            "مطار الوجه المحلي",
            "زيلفي",
            "العلا",
            "الحلة",
            "شرورة",
            "القطيف",
            "عسير",
            "الباحة",
            "خميس مشيات",
            "محايل"
        ];
        // for ($i = 0; $i < 2; $i++) {
        $country = Country::create(
            [
                'en' => [
                    'country_name' => $countries_en[0],
                ],
                'ar' => [
                    'country_name' => $countries_ar[0],
                ]
            ]
        );
        for ($j = 0; $j < count($saudiaCities_en); $j++) {
            City::create([
                'country_id' => $country->id,

                'en' => [
                    'city_name' => $saudiaCities_en[$j],
                ],
                'ar' => [
                    'city_name' => $saudiaCities_ar[$j],
                ]

            ]);
        }
        // }

        //Egypt cities
        $egyptCities_en = [
            "Marina",
            "Suez",
            "Soma Bay",
            "Ain Sukhna",
            "El-Tor",
            "King Mariout",
            "Makadi Bay",
            "Soma Bay",
            "El Gouna",
            "Agouza",
            "New Cairo",
            "Maadi",
            "Nasr City ",
            "Giza",
            "Dokki",
            "Zamalek",
            "Heliopolis",
            "West bank",
            "East bank",
            "El-Shaikh Mabrouk",
            "Abu Dabab",
            "Port Said",
            "Dakhla Oasis",
            "Ain Sokhna",
            "Coraya Bay",
            "Port Ghalib",
            "Marsa Alam",
            "Saint Catherine",
            "Abu Simbel",
            "El Alamein",
            "El Arish",
            "Bawati",
            "Fayoum",
            "Hurghada",
            "Alexandria",
            "Ismailia",
            "6th Of October",
            "Al Mahallah Al Kubra",
            "Cairo",
            "Quseir",
            "Luxor",
            "Aswan",
            "Borg El Arab",
            "Safaga ",
            "Dahab",
            "Sidi Krir ",
            "Madinat Al Ashir min Ramadan",
            "Marsa Alam City",
            "Marsa Matruh",
            "Nuweiba",
            "Qasr Al Farafirah",
            "Ras Matarma",
            "Ras Sedr",
            "Shakshuk",
            "Sharm El Sheikh",
            "Siwa",
            "Taba",
            "Abu Soma",
            "Asyut",
            "Berenice",
            "Hamata",
            "Kalawy Bay",
            "Minya",
            "Na'ama Bay",
            "Nabq",
            "Qena",
            "Ras Nasrani",
            "Ras Om El Seid",
            "Ras Sudr",
            "Sahl Hasheesh",
            "Shark's Bay",
            "Sharm el Naga",
            "Taba Heights",
            "Tondoba Bay",
            "Wadi Gimal",
            "6TH OCTOBER CITY",
            "ABU RUDEIS",
            "ABU SOMA",
            "ABUSIMBEL",
            "AL ARISH",
            "ASSIUT",
            "DABAA CITY",
            "EL FAYOUM",
            "EL MINYA",
            "FARAFRA",
            "KHARGA",
            "MERSA MATRUH",
            "NEW CAIRO CITY",
            "NILE RIVER",
            "NORTH COAST",
            "RAMADAN",
            "RAS SUDR",
            "SANTA KATARINA",
            "SHARK ALOWAINAT",
            "SIDI BARANI",
            "SOUTH SINAI",
            "ST. CATHERINE",
            "TOUR SINAI CITY",
            "Ras Um El Sid",
            "Beni Suef",
            "Egypt",
            "Sinai",
            "El Naaba",
            "El Tur",
            "CAIRO AIRPORT"
        ];
        $egyptCities_ar = [
            "مارينا",
            "السويس",
            "خليج سوما",
            "العين السخنة",
            "الطور",
            "كينج مريوط",
            "خليج مكادي",
            "خليج سوما",
            "الجونة",
            "العجوزة",
            "القاهرة الجديدة",
            "المعادي",
            "مدينة ناصر ",
            "الجيزة",
            "الدقي",
            "الزمالك",
            "مصر الجديدة",
            "الضفة الغربية",
            "الضفة الشرقية",
            "الشيخ مبروك",
            "أبو دباب",
            "بورسعيد",
            "واحة الداخلة",
            "العين السخنة",
            "خليج كورايا",
            "بورت غالب",
            "مرسى علم ",
            "سانت كاترين",
            "أبو سمبل",
            "العلمين",
            "العريش",
            "البواتي",
            "الفيوم",
            "الغردقة",
            "الإسكندرية",
            "الإسماعيلية",
            "6 أكتوبر",
            "المحلة الكبرى",
            "القاهرة",
            "القصير",
            "الأقصر",
            "أسوان",
            "برج العرب",
            "سفاجا",
            "دهب",
            "سيدي كرير",
            "مدينة العاشر من رمضان",
            "مدينة مرسى علم",
            "مرسى مطروح",
            "نويبع",
            "قصر الفرافرة",
            "رأس المطارمة",
            "رأس سدر",
            "شكشوك",
            "شرم الشيخ",
            "سيوة",
            "طابا",
            "أبو سومة",
            "أسيوط",
            "برنيس",
            "حماطة",
            "خليج كلاوي",
            "المنيا",
            "خليج نعمة",
            "نبق",
            "قنا",
            "رأس نصراني",
            "رأس أم السيد",
            "رأس سدر",
            "سهل حشيش",
            "خليج القرش",
            "شرم النجا",
            "مرتفعات طابا",
            "خليج تندوبا",
            "وادي جمال",
            "مدينة 6 أكتوبر",
            "أبو روديس",
            "أبو سوما",
            "أبو سمبل",
            "العريش",
            "أسيوط",
            "مدينة الضبعة",
            "الفيوم",
            "المنيا",
            "فرافرة",
            "الخرطوم",
            "مرسى مطروح",
            "مدينة القاهرة الجديدة",
            "نهر النيل",
            "الساحل الشمالي",
            "رمضان",
            "رأس سودر",
            "سانتا كاتارينا",
            "شارك العوينات",
            "سيدي براني",
            "جنوب سيناء",
            "سانت كاترين",
            "جولة في مدينة سيناء",
            "رأس أم السيد",
            "بني سويف",
            "مصر",
            "سيناء",
            "النبع",
            "الطور",
            "مطار القاهرة"
        ];
        $country = Country::create(
            [
                'en' => [
                    'country_name' => $countries_en[1],
                ],
                'ar' => [
                    'country_name' => $countries_ar[1],
                ]
            ]
        );
        for ($j = 0; $j < count($egyptCities_en); $j++) {
            City::create([
                'country_id' => $country->id,

                'en' => [
                    'city_name' => $egyptCities_en[$j],
                ],
                'ar' => [
                    'city_name' => $egyptCities_ar[$j],
                ]

            ]);
        }
    }
}
